---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: soccer-news-mcp
  labels:
    app: soccer-news-mcp
spec:
  to:
    kind: Service
    name: soccer-news-mcp
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
